//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Starward.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreLang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Starward.Core.Localization.CoreLang", typeof(CoreLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot parse the warp record URL. 的本地化字符串。
        /// </summary>
        internal static string Gacha_CannotParseTheWarpRecordURL {
            get {
                return ResourceManager.GetString("Gacha_CannotParseTheWarpRecordURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot parse the wish record URL. 的本地化字符串。
        /// </summary>
        internal static string Gacha_CannotParseTheWishRecordURL {
            get {
                return ResourceManager.GetString("Gacha_CannotParseTheWishRecordURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Character Event Warp 的本地化字符串。
        /// </summary>
        internal static string GachaType_CharacterEventWarp {
            get {
                return ResourceManager.GetString("GachaType_CharacterEventWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Character Event Wish 的本地化字符串。
        /// </summary>
        internal static string GachaType_CharacterEventWish {
            get {
                return ResourceManager.GetString("GachaType_CharacterEventWish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Character Event Wish - 2 的本地化字符串。
        /// </summary>
        internal static string GachaType_CharacterEventWish_2 {
            get {
                return ResourceManager.GetString("GachaType_CharacterEventWish_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chronicled Wish 的本地化字符串。
        /// </summary>
        internal static string GachaType_ChronicledWish {
            get {
                return ResourceManager.GetString("GachaType_ChronicledWish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Departure Warp 的本地化字符串。
        /// </summary>
        internal static string GachaType_DepartureWarp {
            get {
                return ResourceManager.GetString("GachaType_DepartureWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light Cone Event Warp 的本地化字符串。
        /// </summary>
        internal static string GachaType_LightConeEventWarp {
            get {
                return ResourceManager.GetString("GachaType_LightConeEventWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Novice Wish 的本地化字符串。
        /// </summary>
        internal static string GachaType_NoviceWish {
            get {
                return ResourceManager.GetString("GachaType_NoviceWish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permanent Wish 的本地化字符串。
        /// </summary>
        internal static string GachaType_PermanentWish {
            get {
                return ResourceManager.GetString("GachaType_PermanentWish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stellar Warp 的本地化字符串。
        /// </summary>
        internal static string GachaType_StellarWarp {
            get {
                return ResourceManager.GetString("GachaType_StellarWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weapon Event Wish 的本地化字符串。
        /// </summary>
        internal static string GachaType_WeaponEventWish {
            get {
                return ResourceManager.GetString("GachaType_WeaponEventWish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Genshin Impact 的本地化字符串。
        /// </summary>
        internal static string Game_GenshinImpact {
            get {
                return ResourceManager.GetString("Game_GenshinImpact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Honkai Impact 3rd 的本地化字符串。
        /// </summary>
        internal static string Game_HonkaiImpact3rd {
            get {
                return ResourceManager.GetString("Game_HonkaiImpact3rd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Honkai: Star Rail 的本地化字符串。
        /// </summary>
        internal static string Game_HonkaiStarRail {
            get {
                return ResourceManager.GetString("Game_HonkaiStarRail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bilibili Server 的本地化字符串。
        /// </summary>
        internal static string GameServer_BilibiliServer {
            get {
                return ResourceManager.GetString("GameServer_BilibiliServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 China Cloud Server 的本地化字符串。
        /// </summary>
        internal static string GameServer_ChinaCloudServer {
            get {
                return ResourceManager.GetString("GameServer_ChinaCloudServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 China Server 的本地化字符串。
        /// </summary>
        internal static string GameServer_ChinaServer {
            get {
                return ResourceManager.GetString("GameServer_ChinaServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Europe &amp; Americas Servers 的本地化字符串。
        /// </summary>
        internal static string GameServer_EuropeAmericasServers {
            get {
                return ResourceManager.GetString("GameServer_EuropeAmericasServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global Server 的本地化字符串。
        /// </summary>
        internal static string GameServer_GlobalServer {
            get {
                return ResourceManager.GetString("GameServer_GlobalServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Japan Server 的本地化字符串。
        /// </summary>
        internal static string GameServer_JapanServer {
            get {
                return ResourceManager.GetString("GameServer_JapanServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Korea Server 的本地化字符串。
        /// </summary>
        internal static string GameServer_KoreaServer {
            get {
                return ResourceManager.GetString("GameServer_KoreaServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Southeast Asia Server 的本地化字符串。
        /// </summary>
        internal static string GameServer_SEAServer {
            get {
                return ResourceManager.GetString("GameServer_SEAServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traditional Chinese Server 的本地化字符串。
        /// </summary>
        internal static string GameServer_TraditionalChineseServer {
            get {
                return ResourceManager.GetString("GameServer_TraditionalChineseServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Artifacts 的本地化字符串。
        /// </summary>
        internal static string GenshinQueryType_Artifact {
            get {
                return ResourceManager.GetString("GenshinQueryType_Artifact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Genesis Crystals 的本地化字符串。
        /// </summary>
        internal static string GenshinQueryType_GenesisCrystal {
            get {
                return ResourceManager.GetString("GenshinQueryType_GenesisCrystal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original Resins 的本地化字符串。
        /// </summary>
        internal static string GenshinQueryType_OriginalResin {
            get {
                return ResourceManager.GetString("GenshinQueryType_OriginalResin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Primogems 的本地化字符串。
        /// </summary>
        internal static string GenshinQueryType_Primogem {
            get {
                return ResourceManager.GetString("GenshinQueryType_Primogem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weapons 的本地化字符串。
        /// </summary>
        internal static string GenshinQueryType_Weapon {
            get {
                return ResourceManager.GetString("GenshinQueryType_Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Events 的本地化字符串。
        /// </summary>
        internal static string PostType_Activity {
            get {
                return ResourceManager.GetString("PostType_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notices 的本地化字符串。
        /// </summary>
        internal static string PostType_Announcement {
            get {
                return ResourceManager.GetString("PostType_Announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        internal static string PostType_Information {
            get {
                return ResourceManager.GetString("PostType_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light Cone 的本地化字符串。
        /// </summary>
        internal static string StarRailQueryType_LightCone {
            get {
                return ResourceManager.GetString("StarRailQueryType_LightCone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oneiric Shared 的本地化字符串。
        /// </summary>
        internal static string StarRailQueryType_OneiricShared {
            get {
                return ResourceManager.GetString("StarRailQueryType_OneiricShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Relic 的本地化字符串。
        /// </summary>
        internal static string StarRailQueryType_Relic {
            get {
                return ResourceManager.GetString("StarRailQueryType_Relic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stellar Jade 的本地化字符串。
        /// </summary>
        internal static string StarRailQueryType_StellarJade {
            get {
                return ResourceManager.GetString("StarRailQueryType_StellarJade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trailblaze Power 的本地化字符串。
        /// </summary>
        internal static string StarRailQueryType_TrailblazePower {
            get {
                return ResourceManager.GetString("StarRailQueryType_TrailblazePower", resourceCulture);
            }
        }
    }
}
