name: Bug Report
description: Report a bug
title: "[Bug] "
labels: ["triage"]
body:

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Your issue may be closed without any reply if duplicate.
      options:
        - label: My issue was not mentioned by others, and it is not a duplicate issue.
          required: true

  - type: textarea
    id: bug
    attributes:
      label: Description
      description: Please enter a short, clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: step
    attributes:
      label: Reproduction Steps
      description: Please provide any required setup and steps to reproduce the behavior.
    validations:
      required: true

  - type: textarea
    id: behavior
    attributes:
      label: Expected Behavior
      description: Please provide a description of what you expected to happen.

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots
      description: If applicable, add screenshots here to help explain your problem.

  - type: input
    id: starward_ver
    attributes:
      label: Starward Version
      placeholder:
    validations:
      required: true

  - type: input
    id: win_ver
    attributes:
      label: Windows Version
      placeholder: "Example: 22621.1928"
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: Log
      description: Please upload log file.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Enter any other applicable info here.
