//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Starward.Setup.Locale {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Starward.Setup.Locale.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 All files can be safely deleted. 的本地化字符串。
        /// </summary>
        internal static string AllFilesCanBeSafelyDeleted {
            get {
                return ResourceManager.GetString("AllFilesCanBeSafelyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred during installation 的本地化字符串。
        /// </summary>
        internal static string AnErrorOccurredDuringInstallation {
            get {
                return ResourceManager.GetString("AnErrorOccurredDuringInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred during the update 的本地化字符串。
        /// </summary>
        internal static string AnErrorOccurredDuringTheUpdate {
            get {
                return ResourceManager.GetString("AnErrorOccurredDuringTheUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred during uninstallation 的本地化字符串。
        /// </summary>
        internal static string AnErrorOccurredDuringUninstallation {
            get {
                return ResourceManager.GetString("AnErrorOccurredDuringUninstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A setup program is already running. 的本地化字符串。
        /// </summary>
        internal static string ASetupIsAlreadyRunning {
            get {
                return ResourceManager.GetString("ASetupIsAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check failed. Unable to guarantee the safety of the uninstallation operation. 的本地化字符串。
        /// </summary>
        internal static string CannotGuaranteeSafetyOfUninstallation {
            get {
                return ResourceManager.GetString("CannotGuaranteeSafetyOfUninstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change 的本地化字符串。
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game Launcher for miHoYo 的本地化字符串。
        /// </summary>
        internal static string GameLauncherForMiHoYo {
            get {
                return ResourceManager.GetString("GameLauncherForMiHoYo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I acknowledge the above risks 的本地化字符串。
        /// </summary>
        internal static string IAcknowledgeTheAboveRisks {
            get {
                return ResourceManager.GetString("IAcknowledgeTheAboveRisks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I have read and agree to the Privacy Policy 的本地化字符串。
        /// </summary>
        internal static string IHaveReadAndAgreeToThePrivacyPolicy {
            get {
                return ResourceManager.GetString("IHaveReadAndAgreeToThePrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install 的本地化字符串。
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep cached data 的本地化字符串。
        /// </summary>
        internal static string KeepCachedData {
            get {
                return ResourceManager.GetString("KeepCachedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your OS version is below Windows 10 1809 (Build 17763). Please upgrade to the latest version of Windows to continue installing Starward. 的本地化字符串。
        /// </summary>
        internal static string OSVersionLessThan17763 {
            get {
                return ResourceManager.GetString("OSVersionLessThan17763", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected folder is on a removable device. It is recommended to download the Portable version. 的本地化字符串。
        /// </summary>
        internal static string RemovableDeviceDownloadPortable {
            get {
                return ResourceManager.GetString("RemovableDeviceDownloadPortable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Space Available 的本地化字符串。
        /// </summary>
        internal static string SpaceAvailable {
            get {
                return ResourceManager.GetString("SpaceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Space Required 的本地化字符串。
        /// </summary>
        internal static string SpaceRequired {
            get {
                return ResourceManager.GetString("SpaceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starward ({0}) is running. Do you want to force close it? 的本地化字符串。
        /// </summary>
        internal static string StarwardIsRunningForceClose {
            get {
                return ResourceManager.GetString("StarwardIsRunningForceClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starward, Launch! 的本地化字符串。
        /// </summary>
        internal static string StarwardLaunch {
            get {
                return ResourceManager.GetString("StarwardLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starward Setup 的本地化字符串。
        /// </summary>
        internal static string StarwardSetup {
            get {
                return ResourceManager.GetString("StarwardSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starward Uninstaller 的本地化字符串。
        /// </summary>
        internal static string StarwardUninstaller {
            get {
                return ResourceManager.GetString("StarwardUninstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starward Updater 的本地化字符串。
        /// </summary>
        internal static string StarwardUpdater {
            get {
                return ResourceManager.GetString("StarwardUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The destination folder does not exist. Please try again. 的本地化字符串。
        /// </summary>
        internal static string TheDestinationFolderDoesNotExistPleaseTryAgain {
            get {
                return ResourceManager.GetString("TheDestinationFolderDoesNotExistPleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uninstall 的本地化字符串。
        /// </summary>
        internal static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uninstallation Complete 的本地化字符串。
        /// </summary>
        internal static string UninstallationComplete {
            get {
                return ResourceManager.GetString("UninstallationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The installation path is incorrect or the folder has been moved. To avoid accidentally deleting files, the uninstall function is disabled. Please delete the files manually. 的本地化字符串。
        /// </summary>
        internal static string UninstallPathCaution {
            get {
                return ResourceManager.GetString("UninstallPathCaution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The database file StarwardDatabase.db exists in the installation directory. Personal data will be lost after uninstallation. 的本地化字符串。
        /// </summary>
        internal static string UnstallDatabaseCaution {
            get {
                return ResourceManager.GetString("UnstallDatabaseCaution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Game screenshot files exist in the installation directory. These files will be deleted after uninstallation. 的本地化字符串。
        /// </summary>
        internal static string UnstallScreenshotCaution {
            get {
                return ResourceManager.GetString("UnstallScreenshotCaution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
