//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Starward.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreLang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Starward.Core.Localization.CoreLang", typeof(CoreLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot parse the warp record URL. 的本地化字符串。
        /// </summary>
        internal static string Gacha_CannotParseTheWarpRecordURL {
            get {
                return ResourceManager.GetString("Gacha_CannotParseTheWarpRecordURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot parse the wish record URL. 的本地化字符串。
        /// </summary>
        internal static string Gacha_CannotParseTheWishRecordURL {
            get {
                return ResourceManager.GetString("Gacha_CannotParseTheWishRecordURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Character Event Warp 的本地化字符串。
        /// </summary>
        internal static string GachaType_CharacterEventWarp {
            get {
                return ResourceManager.GetString("GachaType_CharacterEventWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Character Event Wish 的本地化字符串。
        /// </summary>
        internal static string GachaType_CharacterEventWish {
            get {
                return ResourceManager.GetString("GachaType_CharacterEventWish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Character Event Wish - 2 的本地化字符串。
        /// </summary>
        internal static string GachaType_CharacterEventWish_2 {
            get {
                return ResourceManager.GetString("GachaType_CharacterEventWish_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Departure Warp 的本地化字符串。
        /// </summary>
        internal static string GachaType_DepartureWarp {
            get {
                return ResourceManager.GetString("GachaType_DepartureWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light Cone Event Warp 的本地化字符串。
        /// </summary>
        internal static string GachaType_LightConeEventWarp {
            get {
                return ResourceManager.GetString("GachaType_LightConeEventWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Novice Wish 的本地化字符串。
        /// </summary>
        internal static string GachaType_NoviceWish {
            get {
                return ResourceManager.GetString("GachaType_NoviceWish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permanent Wish 的本地化字符串。
        /// </summary>
        internal static string GachaType_PermanentWish {
            get {
                return ResourceManager.GetString("GachaType_PermanentWish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stellar Warp 的本地化字符串。
        /// </summary>
        internal static string GachaType_StellarWarp {
            get {
                return ResourceManager.GetString("GachaType_StellarWarp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weapon Event Wish 的本地化字符串。
        /// </summary>
        internal static string GachaType_WeaponEventWish {
            get {
                return ResourceManager.GetString("GachaType_WeaponEventWish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Events 的本地化字符串。
        /// </summary>
        internal static string PostType_Activity {
            get {
                return ResourceManager.GetString("PostType_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notices 的本地化字符串。
        /// </summary>
        internal static string PostType_Announcement {
            get {
                return ResourceManager.GetString("PostType_Announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info 的本地化字符串。
        /// </summary>
        internal static string PostType_Information {
            get {
                return ResourceManager.GetString("PostType_Information", resourceCulture);
            }
        }
    }
}
