//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Starward.Core.ZipStreamDownload.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZipStreamDownload.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File CRC check failed: {0}.
        /// </summary>
        internal static string CrcVerificationFailedExceptionMessage {
            get {
                return ResourceManager.GetString("CrcVerificationFailedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to access a path that is not on the disk: {0}.
        /// </summary>
        internal static string DirectoryNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("DirectoryNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This compressed file uses features that are not supported by this library, reason: {0}.
        /// </summary>
        internal static string FeatureNotSupportedExceptionMessage {
            get {
                return ResourceManager.GetString("FeatureNotSupportedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The actual size of the body does not match the parameters in the header..
        /// </summary>
        internal static string HttpBodyLengthNotMatchExceptionMessage {
            get {
                return ResourceManager.GetString("HttpBodyLengthNotMatchExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file on HTTP server are modified during partial download..
        /// </summary>
        internal static string HttpFileModifiedDuringPartialDownloadMessage {
            get {
                return ResourceManager.GetString("HttpFileModifiedDuringPartialDownloadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The media type returned by the HTTP server is not the required file type..
        /// </summary>
        internal static string HttpMediaTypeMismatchExceptionMessage {
            get {
                return ResourceManager.GetString("HttpMediaTypeMismatchExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This HTTP server may not support partial download..
        /// </summary>
        internal static string HttpServerNotSupportedPartialDownloadExceptionMessage {
            get {
                return ResourceManager.GetString("HttpServerNotSupportedPartialDownloadExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response code returned by the HTTP server is invalid, code: {0}, message: {1}.
        /// </summary>
        internal static string HttpStatusCodeInvalidExceptionMessage {
            get {
                return ResourceManager.GetString("HttpStatusCodeInvalidExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name in the ZIP local file header is invalid, unable to find the file name: {0}.
        /// </summary>
        internal static string ZipEntryFileNameNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("ZipEntryFileNameNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZipEntry must be a file entry..
        /// </summary>
        internal static string ZipEntryNotIsFileArgumentExceptionMessage {
            get {
                return ResourceManager.GetString("ZipEntryNotIsFileArgumentExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP central directory record test failed, reason: {0}.
        /// </summary>
        internal static string ZipFileTestFailedExceptionCentralDirectoryMessage {
            get {
                return ResourceManager.GetString("ZipFileTestFailedExceptionCentralDirectoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP file test failed: {0}, reason: {1}.
        /// </summary>
        internal static string ZipFileTestFailedExceptionMessage {
            get {
                return ResourceManager.GetString("ZipFileTestFailedExceptionMessage", resourceCulture);
            }
        }
    }
}
