//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Starward.Core.ZipStreamDownload.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages_zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages_zh_CN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Starward.Core.ZipStreamDownload.Resources.ExceptionMessages.zh-CN", typeof(ExceptionMessages_zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件CRC校验失败：{0}.
        /// </summary>
        internal static string CrcVerificationFailedExceptionMessage {
            get {
                return ResourceManager.GetString("CrcVerificationFailedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 试图访问不在磁盘上的路径：{0}.
        /// </summary>
        internal static string DirectoryNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("DirectoryNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该压缩文件使用了不受此库支持的特性，原因：{0}.
        /// </summary>
        internal static string FeatureNotSupportedExceptionMessage {
            get {
                return ResourceManager.GetString("FeatureNotSupportedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP请求体的实际大小与请求头中的相关参数不匹配。.
        /// </summary>
        internal static string HttpBodyLengthNotMatchExceptionMessage {
            get {
                return ResourceManager.GetString("HttpBodyLengthNotMatchExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP服务器上的文件在分段下载时被修改了。.
        /// </summary>
        internal static string HttpFileModifiedDuringPartialDownloadMessage {
            get {
                return ResourceManager.GetString("HttpFileModifiedDuringPartialDownloadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP服务器返回的文件类型不是当前需要的文件类型。.
        /// </summary>
        internal static string HttpMediaTypeMismatchExceptionMessage {
            get {
                return ResourceManager.GetString("HttpMediaTypeMismatchExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该HTTP服务器可能不支持分段下载功能。.
        /// </summary>
        internal static string HttpServerNotSupportedPartialDownloadExceptionMessage {
            get {
                return ResourceManager.GetString("HttpServerNotSupportedPartialDownloadExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP服务器返回的响应代码无效，无效代码：{0}，描述：{1}.
        /// </summary>
        internal static string HttpStatusCodeInvalidExceptionMessage {
            get {
                return ResourceManager.GetString("HttpStatusCodeInvalidExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP实体文件头中的名称无效，无法找到文件名称：{0}.
        /// </summary>
        internal static string ZipEntryFileNameNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("ZipEntryFileNameNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZipEntry实例必须为文件。.
        /// </summary>
        internal static string ZipEntryNotIsFileArgumentExceptionMessage {
            get {
                return ResourceManager.GetString("ZipEntryNotIsFileArgumentExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP实体文件头测试失败，原因：{0}.
        /// </summary>
        internal static string ZipFileTestFailedExceptionCentralDirectoryMessage {
            get {
                return ResourceManager.GetString("ZipFileTestFailedExceptionCentralDirectoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP文件测试失败：{0}，原因：{1}.
        /// </summary>
        internal static string ZipFileTestFailedExceptionMessage {
            get {
                return ResourceManager.GetString("ZipFileTestFailedExceptionMessage", resourceCulture);
            }
        }
    }
}
