
name: Publish Dev

on:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write


jobs:

  version:
    runs-on: windows-latest
    outputs: 
      version: ${{ steps.generate_version.outputs.version }}
    steps:
    - name: Generate Version
      id: generate_version
      run: |
        $id = (Get-Date).ToString('yyMMddHHmm')
        $version = "0.0.1-dev.$id"
        echo "version=$version" >> $env:GITHUB_OUTPUT


  build:
    runs-on: windows-latest
    needs: version
    outputs:
      version: ${{ needs.version.outputs.version }}
    strategy:
      matrix:
        platform: [x64, arm64]
    env:
      Platform: ${{ matrix.platform }}
      Version: ${{ needs.version.outputs.version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        global-json-file: global.json

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: ./build.ps1 -Architecture $env:Platform -Version $env:Version -Dev

    - name: Create Metadata
      run: ./metadata.ps1 -Architecture $env:Platform -Version $env:Version -Dev

    - name: Setup OssUtil
      run: |
        Invoke-WebRequest https://gosspublic.alicdn.com/ossutil/1.7.19/ossutil-v1.7.19-windows-amd64.zip -OutFile ${{runner.temp}}/ossutil.zip
        Expand-Archive -Path ${{runner.temp}}/ossutil.zip -DestinationPath ${{runner.temp}}
        Move-Item -Path ${{runner.temp}}/ossutil-v1.7.19-windows-amd64/ossutil64.exe -Destination C:/Windows/System32/ossutil.exe -Force
        ossutil config -e ${{ secrets.OSS_ENDPOINT }} -i ${{ secrets.ACCESS_KEY_ID }} -k ${{ secrets.ACCESS_KEY_SECRET }}

    - name: Upload to OSS
      run: ossutil cp -rf ./build/release/ oss://starward/release/ --meta Content-Type:multipart/mixed

    - name: Upload Metadata
      uses: actions/upload-artifact@v4
      with:
        name: metadata_${{ matrix.platform }}
        path: build/metadata/

    - name: Upload Release
      uses: actions/upload-artifact@v4
      with:
        name: Starward_Portable_${{ needs.version.outputs.version }}_${{ matrix.platform }}
        path: build/release/package/dev/Starward_Portable_${{ needs.version.outputs.version }}_${{ matrix.platform }}.7z


  metadata:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Metadata
      uses: actions/checkout@v4
      with:
        ref: metadata

    - name: Download Artifact x64
      uses: actions/download-artifact@v4
      with:
        name: metadata_x64

    - name: Download Artifact arm64
      uses: actions/download-artifact@v4
      with:
        name: metadata_arm64

    - name: Push Metadata
      shell: pwsh
      run: |
        $shortSha = "${{ github.sha }}".Substring(0, 7)
        git config --global user.name '${{ github.actor }}'
        git config --global user.email '${{ github.actor }}@users.noreply.github.com'
        git commit -am "update metadata ${{ needs.build.outputs.version }} ($shortSha)"
        git push

    - name: Upload to OSS
      run: |
        rm -rf ./.git ./.github
        curl https://gosspublic.alicdn.com/ossutil/install.sh | sudo bash
        ossutil config -e ${{ secrets.OSS_ENDPOINT }} -i ${{ secrets.ACCESS_KEY_ID }} -k ${{ secrets.ACCESS_KEY_SECRET }}
        ossutil cp -rf ./ oss://starward/metadata/        
        
